services:
  - type: web
    name: semantic-segmentation
    runtime: python
    pythonVersion: "3.11.11"  # Match Render's default
    buildCommand: bash build.sh
    startCommand: streamlit run areapercentage.py --server.port $PORT
