services:
  - type: web
    name: semantic-segmentation
    runtime: python
    pythonVersion: "3.10.13"
    buildCommand: bash build.sh
    startCommand: python3.10 -m streamlit run areapercentage.py --server.port $PORT